-- USERADMIN 또는 SECURITYADMIN 권한으로 실행 (일반적으로 권한 부여 시 사용)
USE ROLE USERADMIN;

-- 팀원의 Snowflake 계정 이름(예: JOHN_DOE)에 TEAM_ROLE 부여
GRANT ROLE TEAM_ROLE TO USER 팀원_계정_이름;


select * from PROJECT_DB.SHARED_FILES.SANGA_22;


CREATE OR REPLACE VIEW PROJECT_DB.SHARED_FILES.SANGA_ALL AS
SELECT *, '21' AS SOURCE_TABLE FROM PROJECT_DB.SHARED_FILES.SANGA_21
UNION ALL
SELECT *, '22' AS SOURCE_TABLE FROM PROJECT_DB.SHARED_FILES.SANGA_22
UNION ALL
SELECT *, '23' AS SOURCE_TABLE FROM PROJECT_DB.SHARED_FILES.SANGA_23
UNION ALL
SELECT *, '24' AS SOURCE_TABLE FROM PROJECT_DB.SHARED_FILES.SANGA_24
UNION ALL
SELECT *, '25' AS SOURCE_TABLE FROM PROJECT_DB.SHARED_FILES.SANGA_25
UNION ALL
SELECT *, '26' AS SOURCE_TABLE FROM PROJECT_DB.SHARED_FILES.SANGA_26;


SELECT * FROM PROJECT_DB.SHARED_FILES.SANGA_ALL;

SELECT * FROM FS_ALL;


