CREATE OR REPLACE VIEW V_COHORT AS

WITH COHORTS AS (

    SELECT 2021 AS COHORT_YEAR, TO_DATE('2021-01-01') AS T
    UNION ALL
    SELECT 2022, TO_DATE('2022-01-01')
    UNION ALL
    SELECT 2023, TO_DATE('2023-01-01')
    UNION ALL
    SELECT 2024, TO_DATE('2024-01-01')

),

BASE AS (

    SELECT
        F.*,
        TRY_TO_DATE(F.LICENSE_DATE) AS LICENSE_DT,
        TRY_TO_DATE(F.CLOSE_DATE) AS CLOSE_DT

    FROM FOOD_ALL F

)

SELECT
    B.*,

    C.COHORT_YEAR,
    C.T AS COHORT_DATE,

    CASE
        WHEN B.CLOSE_DT > C.T
         AND B.CLOSE_DT <= DATEADD(MONTH, 24, C.T)
        THEN 1
        ELSE 0
    END AS Y_CLOSED_24M

FROM BASE B

JOIN COHORTS C
  ON B.LICENSE_DT <= C.T
 AND (
        B.CLOSE_DT IS NULL
        OR B.CLOSE_DT > C.T
     );

SELECT * FROM V_COHORT;

SELECT
    COHORT_YEAR,
    COUNT(*) AS N,
    SUM(Y_CLOSED_24M) AS CLOSED_N,
    ROUND(AVG(Y_CLOSED_24M) * 100, 2) AS CLOSED_RATE_PCT
FROM V_COHORT
GROUP BY COHORT_YEAR
ORDER BY COHORT_YEAR;


SELECT COUNT(*) AS INVALID_CNT
FROM V_COHORT
WHERE CLOSE_DATE IS NOT NULL
  AND TRY_TO_DATE(CLOSE_DATE) <= COHORT_DATE;

  SELECT COUNT(*) AS INVALID_CNT
FROM V_COHORT
WHERE TRY_TO_DATE(LICENSE_DATE) > COHORT_DATE;




SELECT
    SHOP_ID,
    SHOP_NAME,
    COHORT_YEAR,
    COHORT_DATE,
    LICENSE_DATE,
    CLOSE_DATE,
    Y_CLOSED_24M
FROM V_COHORT
WHERE Y_CLOSED_24M = 1
LIMIT 30;

SELECT COUNT(*) AS INVALID_Y_CNT
FROM V_COHORT
WHERE Y_CLOSED_24M = 1
  AND (
        CLOSE_DATE IS NULL
        OR TRY_TO_DATE(CLOSE_DATE) <= COHORT_DATE
        OR TRY_TO_DATE(CLOSE_DATE) > DATEADD(MONTH, 24, COHORT_DATE)
      );

SELECT
    COUNT(*) AS ROW_CNT,
    COUNT(DISTINCT SHOP_ID) AS UNIQUE_SHOPS
FROM V_COHORT;

SELECT DISTINCT
    COHORT_YEAR,
    COHORT_DATE
FROM V_COHORT
ORDER BY COHORT_YEAR;


SELECT COUNT(*) AS LABEL_MISMATCH_CNT
FROM V_COHORT
WHERE Y_CLOSED_24M <>
    CASE
        WHEN CLOSE_DATE IS NOT NULL
         AND TRY_TO_DATE(CLOSE_DATE) > COHORT_DATE
         AND TRY_TO_DATE(CLOSE_DATE) <= DATEADD(MONTH, 24, COHORT_DATE)
        THEN 1
        ELSE 0
    END;


CREATE OR REPLACE VIEW V_COHORT AS

WITH COHORTS AS (

    SELECT 2014 AS COHORT_YEAR, TO_DATE('2014-01-01') AS COHORT_DATE, 'PRE' AS PERIOD
    UNION ALL
    SELECT 2015, TO_DATE('2015-01-01'), 'PRE'
    UNION ALL
    SELECT 2016, TO_DATE('2016-01-01'), 'PRE'
    UNION ALL
    SELECT 2017, TO_DATE('2017-01-01'), 'PRE'
    UNION ALL
    SELECT 2018, TO_DATE('2018-01-01'), 'PRE'

    UNION ALL

    SELECT 2021, TO_DATE('2021-01-01'), 'POST'
    UNION ALL
    SELECT 2022, TO_DATE('2022-01-01'), 'POST'
    UNION ALL
    SELECT 2023, TO_DATE('2023-01-01'), 'POST'
),

BASE AS (

    SELECT
        F.*,
        TRY_TO_DATE(F.LICENSE_DATE) AS LICENSE_DT,
        TRY_TO_DATE(F.CLOSE_DATE) AS CLOSE_DT
    FROM FOOD_ALL F
)

SELECT
    B.*,

    C.COHORT_YEAR,
    C.COHORT_DATE,
    C.PERIOD,

    CASE
        WHEN B.CLOSE_DT > C.COHORT_DATE
         AND B.CLOSE_DT <= DATEADD(MONTH, 24, C.COHORT_DATE)
        THEN 1
        ELSE 0
    END AS Y_CLOSED_24M

FROM BASE B

JOIN COHORTS C
    ON B.LICENSE_DT <= C.COHORT_DATE

   AND (
        B.CLOSE_DT IS NULL
        OR B.CLOSE_DT > C.COHORT_DATE
   );


SELECT
    PERIOD,
    COHORT_YEAR,
    COUNT(*) AS N,
    SUM(Y_CLOSED_24M) AS CLOSED_N,
    ROUND(AVG(Y_CLOSED_24M) * 100, 2) AS CLOSED_RATE_PCT
FROM V_COHORT
GROUP BY PERIOD, COHORT_YEAR
ORDER BY COHORT_YEAR;


SELECT
    MOD(
        DEGREES(
            ATAN2(
                127.42718 - 127.42750,
                36.32752 - 36.32870
            )
        ) + 360,
        360
    ) AS ANCHOR_BEARING;



CREATE OR REPLACE VIEW V_GEO AS

WITH BASE AS (

    SELECT
        C.*,

        C.LAT AS LAT_NUM,
        C.LON AS LON_NUM

    FROM V_COHORT C

    WHERE C.LAT IS NOT NULL
      AND C.LON IS NOT NULL

      AND C.LAT BETWEEN 33 AND 39
      AND C.LON BETWEEN 124 AND 132
),

GEO_CALC AS (

    SELECT
        B.*,

        ST_DISTANCE(
            ST_MAKEPOINT(B.LON_NUM, B.LAT_NUM),
            ST_MAKEPOINT(127.42718, 36.32752)
        ) AS DIST_ANCHOR_CALC,

        ST_DISTANCE(
            ST_MAKEPOINT(B.LON_NUM, B.LAT_NUM),
            ST_MAKEPOINT(127.42750, 36.32870)
        ) AS DIST_CENTER,

        MOD(
            DEGREES(
                ATAN2(
                    B.LON_NUM - 127.42750,
                    B.LAT_NUM - 36.32870
                )
            ) + 360,
            360
        ) AS BEARING

    FROM BASE B
),

ANGLE_CALC AS (

    SELECT
        G.*,

        LEAST(
            ABS(G.BEARING - 195.2),
            360 - ABS(G.BEARING - 195.2)
        ) AS ANGLE_DIFF

    FROM GEO_CALC G
)

SELECT
    A.*,

    CASE
        WHEN A.ANGLE_DIFF <= 60
            THEN 'ANCHOR'

        WHEN A.ANGLE_DIFF >= 120
            THEN 'OPPOSITE'

        ELSE 'SIDE'
    END AS SECTOR,

    CASE
        WHEN A.DIST_CENTER <= 300
            THEN '0-300m'

        WHEN A.DIST_CENTER <= 600
            THEN '300-600m'

        WHEN A.DIST_CENTER <= 1000
            THEN '600-1000m'

        ELSE '1000m+'
    END AS CENTER_BAND

FROM ANGLE_CALC A;


SELECT
    SHOP_ID,
    SHOP_NAME,
    PERIOD,
    COHORT_YEAR,
    LAT,
    LON,
    DIST_ANCHOR,
    DIST_ANCHOR_CALC,
    DIST_CENTER,
    BEARING,
    ANGLE_DIFF,
    SECTOR,
    CENTER_BAND,
    Y_CLOSED_24M
FROM V_GEO
LIMIT 30;


SELECT
    SECTOR,
    COUNT(*) AS N,
    SUM(Y_CLOSED_24M) AS CLOSED_N,
    ROUND(AVG(Y_CLOSED_24M) * 100, 1) AS CLOSED_RATE_PCT
FROM V_GEO
WHERE PERIOD = 'POST'
  AND DIST_CENTER <= 300
  AND SECTOR IN ('ANCHOR', 'OPPOSITE')
GROUP BY SECTOR
ORDER BY SECTOR;


CREATE OR REPLACE VIEW V_FOOD_CLEAN AS
SELECT
    SHOP_ID,
    SHOP_NAME,
    BIZ_GROUP,
    SERVICE_TYPE,
    TRY_TO_DATE(LICENSE_DATE) AS LICENSE_DATE,
    TRY_TO_DATE(CLOSE_DATE) AS CLOSE_DATE,
    AREA_SQM,
    ADDR_JIBUN,
    DONG,

    COALESCE(SLOT, 'NA_' || SHOP_ID) AS SLOT,

    LAT,
    LON,

    CASE
        WHEN BIZ_GROUP IN ('식당', '주점')
            THEN '보완재'
        WHEN BIZ_GROUP IN ('카페·음료', '제과·베이커리')
            THEN '경쟁재'
        ELSE '중립'
    END AS ROLE

FROM FOOD_ALL

WHERE ADDR_JIBUN LIKE '대전광역시%'
  AND LAT BETWEEN 36.15 AND 36.55
  AND LON BETWEEN 127.25 AND 127.65
  AND LICENSE_DATE IS NOT NULL;


  SELECT COUNT(*)
FROM V_FOOD_CLEAN;


CREATE OR REPLACE VIEW V_COHORT AS

WITH COHORTS AS (

    SELECT 2014 AS COHORT_YEAR, TO_DATE('2014-01-01') AS COHORT_DATE, 'PRE' AS PERIOD
    UNION ALL
    SELECT 2015, TO_DATE('2015-01-01'), 'PRE'
    UNION ALL
    SELECT 2016, TO_DATE('2016-01-01'), 'PRE'
    UNION ALL
    SELECT 2017, TO_DATE('2017-01-01'), 'PRE'
    UNION ALL
    SELECT 2018, TO_DATE('2018-01-01'), 'PRE'

    UNION ALL

    SELECT 2019, TO_DATE('2019-01-01'), 'COVID'
    UNION ALL
    SELECT 2020, TO_DATE('2020-01-01'), 'COVID'

    UNION ALL

    SELECT 2021, TO_DATE('2021-01-01'), 'POST'
    UNION ALL
    SELECT 2022, TO_DATE('2022-01-01'), 'POST'
    UNION ALL
    SELECT 2023, TO_DATE('2023-01-01'), 'POST'
)

SELECT
    F.*,

    C.COHORT_YEAR,
    C.COHORT_DATE,
    C.PERIOD,

    DATEADD(MONTH, 24, C.COHORT_DATE) AS COHORT_END_DATE,

    DATEDIFF(
        DAY,
        F.LICENSE_DATE,
        C.COHORT_DATE
    ) / 30.44 AS AGE_MONTHS,

    CASE
        WHEN F.CLOSE_DATE > C.COHORT_DATE
         AND F.CLOSE_DATE <= DATEADD(MONTH, 24, C.COHORT_DATE)
        THEN 1
        ELSE 0
    END AS Y_CLOSED_24M

FROM V_FOOD_CLEAN F

JOIN COHORTS C
    ON F.LICENSE_DATE <= C.COHORT_DATE
   AND (
        F.CLOSE_DATE IS NULL
        OR F.CLOSE_DATE > C.COHORT_DATE
   );


SELECT
    PERIOD,
    COHORT_YEAR,
    COUNT(*) AS N,
    SUM(Y_CLOSED_24M) AS CLOSED_N,
    ROUND(
        AVG(Y_CLOSED_24M) * 100,
        2
    ) AS CLOSED_RATE_PCT

FROM V_COHORT

GROUP BY
    PERIOD,
    COHORT_YEAR

ORDER BY
    COHORT_YEAR;


SELECT COUNT(*) AS INVALID_CNT
FROM V_COHORT
WHERE CLOSE_DATE IS NOT NULL
  AND CLOSE_DATE <= COHORT_DATE;


SELECT COUNT(*) AS INVALID_CNT
FROM V_COHORT
WHERE LICENSE_DATE > COHORT_DATE;


SELECT COUNT(*) AS INVALID_Y_CNT
FROM V_COHORT
WHERE Y_CLOSED_24M = 1
  AND (
        CLOSE_DATE IS NULL
        OR CLOSE_DATE <= COHORT_DATE
        OR CLOSE_DATE > DATEADD(MONTH, 24, COHORT_DATE)
      );



CREATE OR REPLACE VIEW V_GEO AS

WITH GEO_CALC AS (

    SELECT
        C.*,

        ST_DISTANCE(
            ST_MAKEPOINT(C.LON, C.LAT),
            ST_MAKEPOINT(127.42718, 36.32752)
        ) AS DIST_ANCHOR,

        ST_DISTANCE(
            ST_MAKEPOINT(C.LON, C.LAT),
            ST_MAKEPOINT(127.42750, 36.32870)
        ) AS DIST_CENTER,

        MOD(
            DEGREES(
                ATAN2(
                    C.LON - 127.42750,
                    C.LAT - 36.32870
                )
            ) + 360,
            360
        ) AS BEARING

    FROM V_COHORT C

    WHERE C.LAT IS NOT NULL
      AND C.LON IS NOT NULL
),

ANGLE_CALC AS (

    SELECT
        G.*,

        LEAST(
            ABS(G.BEARING - 195.2),
            360 - ABS(G.BEARING - 195.2)
        ) AS ANGLE_DIFF

    FROM GEO_CALC G
)

SELECT
    A.*,

    CASE
        WHEN A.ANGLE_DIFF <= 60
            THEN 'ANCHOR'

        WHEN A.ANGLE_DIFF >= 120
            THEN 'OPPOSITE'

        ELSE 'SIDE'
    END AS SECTOR,

    CASE
        WHEN A.DIST_CENTER <= 150
            THEN '0-150m'

        WHEN A.DIST_CENTER <= 300
            THEN '150-300m'

        WHEN A.DIST_CENTER <= 450
            THEN '300-450m'

        WHEN A.DIST_CENTER <= 600
            THEN '450-600m'

        WHEN A.DIST_CENTER <= 800
            THEN '600-800m'

        ELSE '800m+'
    END AS CENTER_BAND

FROM ANGLE_CALC A;


SELECT
    SECTOR,
    COUNT(*) AS N,
    SUM(Y_CLOSED_24M) AS CLOSED_N,
    ROUND(
        AVG(Y_CLOSED_24M) * 100,
        1
    ) AS CLOSED_RATE_PCT

FROM V_GEO

WHERE PERIOD = 'POST'
  AND DIST_CENTER <= 300
  AND SECTOR IN ('ANCHOR', 'OPPOSITE')

GROUP BY SECTOR

ORDER BY SECTOR;


SELECT
    CENTER_BAND,
    SECTOR,
    COUNT(*) AS N,
    ROUND(
        AVG(Y_CLOSED_24M) * 100,
        2
    ) AS CLOSED_RATE_PCT

FROM V_GEO

WHERE PERIOD = 'POST'
  AND SECTOR IN ('ANCHOR', 'OPPOSITE')

GROUP BY
    CENTER_BAND,
    SECTOR

ORDER BY
    CENTER_BAND,
    SECTOR;