CREATE OR REPLACE VIEW V_ROBUST_INPUT AS
SELECT
    SHOP_ID,

    Y_CLOSED_24M AS Y,

    ANGLE_DIFF,
    DIST_CENTER,

    AGE_MONTHS,
    AREA_SQM,
    BIZ_GROUP,

    COHORT_YEAR AS CY,

    SLOT

FROM V_GEO

WHERE PERIOD = 'POST'
  AND DIST_CENTER > 0
  AND DIST_CENTER <= 1000

  AND Y_CLOSED_24M IS NOT NULL
  AND ANGLE_DIFF IS NOT NULL
  AND BIZ_GROUP IS NOT NULL
  AND COHORT_YEAR IS NOT NULL
  AND SLOT IS NOT NULL;


SELECT
    COUNT(*) AS N,
    COUNT(DISTINCT SLOT) AS N_BLOCKS,
    COUNT(DISTINCT SHOP_ID) AS N_SHOPS,
    COUNT_IF(AREA_SQM IS NULL) AS AREA_NULL
FROM V_ROBUST_INPUT;